; # --------------------------------------------------------------------- #
; Copyright (C) 2018 Frederic Meyer. All rights reserved.                 |
;                                                                         |
; Use of this source code is governed by a BSD-style license that can be  |
; found in the LICENSE file.                                              |
; # --------------------------------------------------------------------- #

VM_BASE_KERNEL_ELF equ 0xFFFFFFFF80000000
